<a href="https://colab.research.google.com/github/virendrasinh734/Neural_Networks/blob/main/book_rec2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

In [2]:
# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

!unzip book-crossings.zip

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

--2023-07-22 02:31:31--  https://cdn.freecodecamp.org/project-data/books/book-crossings.zip
Resolving cdn.freecodecamp.org (cdn.freecodecamp.org)... 104.26.3.33, 104.26.2.33, 172.67.70.149, ...
Connecting to cdn.freecodecamp.org (cdn.freecodecamp.org)|104.26.3.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26085508 (25M) [application/zip]
Saving to: ‘book-crossings.zip.1’

book-crossings.zip. 100%[===================>]  24.88M  31.5MB/s    in 0.8s    

2023-07-22 02:31:32 (31.5 MB/s) - ‘book-crossings.zip.1’ saved [26085508/26085508]

Archive:  book-crossings.zip
replace BX-Book-Ratings.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: BX-Book-Ratings.csv     
replace BX-Books.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: BX-Books.csv            
replace BX-Users.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: BX-Users.csv            


In [3]:
# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['isbn', 'title', 'author'],
    usecols=['isbn', 'title', 'author'],
    dtype={'isbn': 'str', 'title': 'str', 'author': 'str'})

df_ratings = pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

In [4]:
print(df_books.shape)
print(df_ratings.shape)

(271379, 3)
(1149780, 3)


In [5]:
df_ratings

user         isbn  rating
0        276725   034545104X     0.0
1        276726   0155061224     5.0
2        276727   0446520802     0.0
3        276729   052165615X     3.0
4        276729   0521795028     6.0
...         ...          ...     ...
1149775  276704   1563526298     9.0
1149776  276706   0679447156     0.0
1149777  276709   0515107662    10.0
1149778  276721   0590442449    10.0
1149779  276723  05162443314     8.0

[1149780 rows x 3 columns]

In [6]:
tot=pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

In [7]:
user_review_counts = df_ratings['user'].value_counts()

book_review_counts = df_ratings['isbn'].value_counts()

filtered_ratings = df_ratings[
    (df_ratings['user'].isin(user_review_counts[user_review_counts > 200].index)) &
    (df_ratings['isbn'].isin(book_review_counts[book_review_counts > 100].index))
]

final_data = filtered_ratings.merge(df_books, on='isbn')



In [8]:
final_data

user        isbn  rating  \
0      277427  002542730X    10.0   
1        3363  002542730X     0.0   
2       11676  002542730X     6.0   
3       12538  002542730X    10.0   
4       13552  002542730X     0.0   
...       ...         ...     ...   
48985  238864  0399149325     0.0   
48986  251843  0399149325     1.0   
48987  253821  0399149325     0.0   
48988  265115  0399149325     0.0   
48989  266226  0399149325     0.0   

                                                   title             author  
0      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
1      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
2      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
3      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
4      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
...                                                  ...                ...  
48985  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48986  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48987  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48988  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48989  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  

[48990 rows x 5 columns]

In [9]:
final_data = filtered_ratings.merge(df_books, on='isbn', suffixes=('_ratings', '_books'))
final_data

user        isbn  rating  \
0      277427  002542730X    10.0   
1        3363  002542730X     0.0   
2       11676  002542730X     6.0   
3       12538  002542730X    10.0   
4       13552  002542730X     0.0   
...       ...         ...     ...   
48985  238864  0399149325     0.0   
48986  251843  0399149325     1.0   
48987  253821  0399149325     0.0   
48988  265115  0399149325     0.0   
48989  266226  0399149325     0.0   

                                                   title             author  
0      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
1      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
2      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
3      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
4      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
...                                                  ...                ...  
48985  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48986  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48987  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48988  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
48989  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  

[48990 rows x 5 columns]

In [10]:
table=final_data.pivot_table(index='title',columns='user',values='rating')
table.fillna(0,inplace=True)
table

user                                                254     2276    2766    \
title                                                                        
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Without Remorse                                        0.0     0.0     0.0   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                2977    3363    4017    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Without Remorse                                        0.0     0.0     0.0   
Year of Wonders                                        7.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                4385    6242    6251    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Without Remorse                                        0.0     0.0     0.0   
Year of Wonders                                        0.0     7.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                6323    ...  274004  \
title                                                       ...           
1984                                                   0.0  ...     0.0   
1st to Die: A Novel                                    0.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0  ...     0.0   
...                                                    ...  ...     ...   
Without Remorse                                        0.0  ...     0.0   
Year of Wonders                                        0.0  ...     0.0   
You Belong To Me                                       0.0  ...     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0   
\O\" Is for Outlaw"                                    

In [11]:
nbrs = NearestNeighbors(n_neighbors=6, algorithm='auto', metric='cosine')
nbrs.fit(table)

# Compute the cosine similarity with indices
similarities, indices = nbrs.kneighbors(table)

# Transform the cosine similarity to get similarity between 0 and 1
closeness =similarities

print(closeness)
print(indices)

[[0.0000000e+00 7.5083876e-01 7.6182473e-01 7.6593226e-01 7.7405274e-01
  7.7445555e-01]
 [5.9604645e-08 7.0653141e-01 7.1565664e-01 7.2228849e-01 7.3945004e-01
  7.4214554e-01]
 [0.0000000e+00 6.0817230e-01 7.1577913e-01 7.1719319e-01 7.1959251e-01
  7.3185676e-01]
 ...
 [0.0000000e+00 4.0097511e-01 4.8801863e-01 5.4811639e-01 5.6834286e-01
  5.8730340e-01]
 [0.0000000e+00 6.4526379e-01 7.1886039e-01 7.6060998e-01 7.6082200e-01
  7.7294624e-01]
 [0.0000000e+00 6.0208690e-01 6.1060166e-01 6.2160534e-01 6.3216466e-01
  6.4200211e-01]]
[[  0 501  50 455 403 503]
 [  1  41 634 371 328 588]
 [  2 193 634 537 544  98]
 ...
 [661 290 242  70 127 648]
 [662 357   9 365 508 427]
 [663 238 267 258 306 159]]


In [12]:
def get_recommends(book = ""):
  ind=np.where(table.index==book)[0][0]
  temp=indices[ind]
  rc=[]

  for i in range(len(temp)-1,1,-1):
    b=table.iloc[temp[i]].name
    s=closeness[ind][i]
    t2=[b,s]
    rc.append(t2)
  recommended_books=[book,rc]


  return recommended_books

In [13]:
books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2):
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉🎉")
  else:
    print("You haven't passed yet. Keep trying!")

test_book_recommendation()

["Where the Heart Is (Oprah's Book Club (Paperback))", [["I'll Be Seeing You", 0.8016211], ['The Weight of Water', 0.77085835], ['The Surgeon', 0.7699411], ['I Know This Much Is True', 0.7677075]]]
You passed the challenge! 🎉🎉🎉🎉🎉
